// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BaseURL() {
  return window['go']['main']['App']['BaseURL']();
}

export function BrowserInput(arg1, arg2) {
  return window['go']['main']['App']['BrowserInput'](arg1, arg2);
}

export function BrowserNavigate(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserNavigate'](arg1, arg2, arg3);
}

export function BrowserSessionInfo(arg1) {
  return window['go']['main']['App']['BrowserSessionInfo'](arg1);
}

export function BrowserSessions(arg1) {
  return window['go']['main']['App']['BrowserSessions'](arg1);
}

export function BrowserSetViewport(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserSetViewport'](arg1, arg2, arg3);
}

export function BrowserTakeover(arg1, arg2) {
  return window['go']['main']['App']['BrowserTakeover'](arg1, arg2);
}

export function BundledChromiumPath() {
  return window['go']['main']['App']['BundledChromiumPath']();
}

export function DecideApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecideApproval'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DenyPlugin(arg1) {
  return window['go']['main']['App']['DenyPlugin'](arg1);
}

export function EnsureBrowserStreamStatus(arg1) {
  return window['go']['main']['App']['EnsureBrowserStreamStatus'](arg1);
}

export function FetchPreviewFile(arg1, arg2) {
  return window['go']['main']['App']['FetchPreviewFile'](arg1, arg2);
}

export function GetAgentConfig(arg1) {
  return window['go']['main']['App']['GetAgentConfig'](arg1);
}

export function GetAgentModelInfo(arg1) {
  return window['go']['main']['App']['GetAgentModelInfo'](arg1);
}

export function GetBrowserEndpoint() {
  return window['go']['main']['App']['GetBrowserEndpoint']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetSessionTurns(arg1) {
  return window['go']['main']['App']['GetSessionTurns'](arg1);
}

export function GetTaskResult(arg1) {
  return window['go']['main']['App']['GetTaskResult'](arg1);
}

export function GrantPlugin(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GrantPlugin'](arg1, arg2, arg3, arg4, arg5);
}

export function HandoffTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandoffTask'](arg1, arg2, arg3);
}

export function InstallBundledChromium() {
  return window['go']['main']['App']['InstallBundledChromium']();
}

export function InterruptTask(arg1) {
  return window['go']['main']['App']['InterruptTask'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListAuditEvents() {
  return window['go']['main']['App']['ListAuditEvents']();
}

export function ListGateableTools() {
  return window['go']['main']['App']['ListGateableTools']();
}

export function ListInbox() {
  return window['go']['main']['App']['ListInbox']();
}

export function ListPendingApprovals() {
  return window['go']['main']['App']['ListPendingApprovals']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListRuntimeEvents() {
  return window['go']['main']['App']['ListRuntimeEvents']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListWorkspaceDir(arg1, arg2) {
  return window['go']['main']['App']['ListWorkspaceDir'](arg1, arg2);
}

export function NewSession(arg1, arg2) {
  return window['go']['main']['App']['NewSession'](arg1, arg2);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenPath(arg1, arg2) {
  return window['go']['main']['App']['OpenPath'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function Port() {
  return window['go']['main']['App']['Port']();
}

export function ReadHTMLFile(arg1) {
  return window['go']['main']['App']['ReadHTMLFile'](arg1);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResolvePlugin(arg1) {
  return window['go']['main']['App']['ResolvePlugin'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SaveAll(arg1, arg2) {
  return window['go']['main']['App']['SaveAll'](arg1, arg2);
}

export function SaveGeneratedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveGeneratedFile'](arg1, arg2);
}

export function SearchWorkspaceContent(arg1, arg2) {
  return window['go']['main']['App']['SearchWorkspaceContent'](arg1, arg2);
}

export function SendAgentMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2);
}

export function ServeStatus() {
  return window['go']['main']['App']['ServeStatus']();
}

export function SetProjectArchived(arg1, arg2) {
  return window['go']['main']['App']['SetProjectArchived'](arg1, arg2);
}

export function SetSessionArchived(arg1, arg2) {
  return window['go']['main']['App']['SetSessionArchived'](arg1, arg2);
}

export function SetSessionMode(arg1, arg2) {
  return window['go']['main']['App']['SetSessionMode'](arg1, arg2);
}

export function SetSessionWorkingDir(arg1, arg2) {
  return window['go']['main']['App']['SetSessionWorkingDir'](arg1, arg2);
}

export function SkillCommand(arg1, arg2) {
  return window['go']['main']['App']['SkillCommand'](arg1, arg2);
}

export function SubmitTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitTask'](arg1, arg2, arg3, arg4);
}
