// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BaseURL():Promise<string>;

export function DecideApproval(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAgentConfig(arg1:string):Promise<main.AgentConfigResult>;

export function GetConfig():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetSessionTurns(arg1:string):Promise<Array<Record<string, any>>>;

export function GetTaskResult(arg1:string):Promise<Record<string, any>>;

export function HandoffTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAgents():Promise<Array<string>>;

export function ListAuditEvents():Promise<Array<Record<string, any>>>;

export function ListInbox():Promise<Array<Record<string, any>>>;

export function ListPendingApprovals():Promise<Array<Record<string, any>>>;

export function ListRuntimeEvents():Promise<Array<Record<string, any>>>;

export function ListSessions():Promise<Array<Record<string, any>>>;

export function ListTasks():Promise<Array<Record<string, any>>>;

export function NewSession(arg1:string,arg2:string):Promise<Record<string, any>>;

export function PickDirectory():Promise<string>;

export function Port():Promise<number>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveAll(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SendAgentMessage(arg1:string,arg2:string):Promise<void>;

export function ServeStatus():Promise<Record<string, any>>;

export function SetProjectArchived(arg1:string,arg2:boolean):Promise<void>;

export function SetSessionArchived(arg1:string,arg2:boolean):Promise<void>;

export function SetSessionMode(arg1:string,arg2:string):Promise<void>;

export function SetSessionWorkingDir(arg1:string,arg2:string):Promise<void>;

export function SkillCommand(arg1:string,arg2:string):Promise<string>;

export function SubmitTask(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;
